config/routes.rb
Rails.application.routes.draw do

  post '/games' => 'game_users#delete', as: 'delete_game_from_user'

  get 'game_user/search' => 'game_users#search', as: 'search'

  post 'game_user/search_result' => 'game_users#search_result', as: 'result'

  resources :user_comments

  get '/comments/:id, :user', to: 'comments#view', as: 'usercomments'

  resources :comments

  resources :friends, only: [:index, :destroy]

  get 'welcome/index'

  resources :home

  resources :game_users

  resources :ratings, only: :update

  resources :games

  resources :profiles

  devise_for :users

  get 'game_user/add_user/:id' => 'game_users#add_user' , as: 'add_user'

  get 'game/add_game/:id' => 'games#add_game' , as: 'add_game'

  root to: "welcome#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :game_user
	belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # raty source: http://paweljaniak.co.za/2013/07/25/5-star-ratings-with-rails/
  # raty jquery source: http://wbotelhos.com/raty
  def view
    #:user ist auch eine id
    @current_user = User.find(params[:user])
    @game_rating_user = GameUser.find(params[:id])
    @comments = Comment.where("gameuser_id = ?", @game_rating_user.id)
    @logo = Game.find(@game_rating_user.game_id).icon

    @rating_entry = Rating.where(game_user_id: @game_rating_user.id, user_id: @current_user.id).first 
    unless 
      @rating_entry = Rating.create(game_user_id: @game_rating_user.id, user_id: @current_user.id, score: 0)
    end
    #@rating = Rating.find(@game_rating_user.rating_id).score
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    puts "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH"
   # @text = params[:comment_text]
   # @game_user = params[:game_user]
   # @user_id = params[:user_id]

    ##puts @text
    #puts @game_user
    #puts @user_id
    puts "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH"

    #@comment = Comment.new(:user_id => @user_id, :gameuser_id => @game_user, :comment_text => @text)
    @comment = Comment.new(comment_params) 


    respond_to do |format|
      if @comment.save
        format.html { redirect_to game_users_path, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:comment_text, :gameuser_id, :user_id)
    end
  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
	
	<% if @comment.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

	      <ul>
	      <% @comment.errors.full_messages.each do |message| %>
	        <li><%= message %></li>
	      <% end %>
	      </ul>
	    </div>
  	<% end %>
  	
  	
	<div class="field">
	   <%= f.label :comment_text %><br>
	   <%= f.text_field :comment_text %>
	</div>
	<%= f.hidden_field :gameuser_id, :value => params[:format] %>
	<%= f.hidden_field :user_id, :value => current_user.id %>
	<div class="actions">
	   <%= f.submit %>
	</div>
<% end %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>
<%= puts "gggggggggggggggggggggggggggGGGGGGGGGGGGGGGGGGGGGGGGGGGGGggggggggggggggggggg" %>
<%= puts params[:format]%>
<% @gu_id = params[:format] %>
<%= puts "gggggggggggggggggggggggggggGGGGGGGGGGGGGGGGGGGGGGGGGGGGGggggggggggggggggggg" %>
<%= render 'form', foo: @gu_id %>

<%= link_to 'Back', game_users_path %>

app/views/comments/show.html.erb
<p>show comment<p>

app/views/comments/view.html.erb
<!-- js source: http://paweljaniak.co.za/2013/07/25/5-star-ratings-with-rails/ -->
<div class="commentHead"><b>User: <%= User.find(@game_rating_user.user_id).name %></b></div>

<table>
<thead>
	<tr>
		<th>Name</th>
		<th>Logo</th>
		<th>Rating</th>
	</tr>
</thead>
<tbody>
	<tr>
		<td>
			<%= Game.find(@game_rating_user.game_id).name%>
		</td>
	
		<td>
			<img class="logos" src="<%= @logo %>"></img>
		</td>

		<td>
			<!--<%=@rating%>-->
			Your rating: 
			<div class="user_star"></div><br>
			Average rating:
			<!-- <div id="star"></div> -->
			<div> <% score = @game_rating_user.average %>
             <% stars_off = 5 - score %>
               <% score.times do %>
                  <img src="../assets/star-on.png"></img>
               <% end %>
               <% stars_off.times do %>
                  <img src="../assets/star-off.png"></img>
               <% end %>
            </div>
		</td>
	</tr>
</tbody>
</table>

<p><%= link_to 'Leave a comment', new_comment_path(@game_rating_user.id)%>
<table>
	<thead>
		<th>comments<th>
	</thead>
	<tbody>
		<% if @comments.first.nil? %>
		<% else %>
			<% @comments.each do |comment| %>
				<tr>
					<td>	
					<div class="commentHead"><h3><%= User.find(comment.user_id).name %> <small style="float:right;" ><%= comment.created_at %></small></h3></div>	
					<small><%= comment.comment_text %></small>
					</td>
				</tr>
			<% end %>
		<% end %>
	</tbody>
</table>


<script>

  $('#star').raty({
    readOnly: true,
    score: <%= @game_rating_user.average_rating %>,
    path: '/assets'
  });

  $('.user_star').raty({
    score: <%= @rating_entry.score%>,
    path: '/assets',
    click: function(score, evt) {
      $.ajax({
        url: '/ratings/' + <%= @rating_entry.id %>,
        type: 'PATCH',
        data: { score: score }
      });
    }
  });
</script>