config/routes.rb
Rails.application.routes.draw do

  post '/games' => 'game_users#delete', as: 'delete_game_from_user'

  get 'game_user/search' => 'game_users#search', as: 'search'

  post 'game_user/search_result' => 'game_users#search_result', as: 'result'

  resources :user_comments

  get '/comments/:id, :user', to: 'comments#view', as: 'usercomments'

  resources :comments

  resources :friends, only: [:index, :destroy]

  get 'welcome/index'

  resources :home

  resources :game_users

  resources :ratings, only: :update

  resources :games

  resources :profiles

  devise_for :users

  get 'game_user/add_user/:id' => 'game_users#add_user' , as: 'add_user'

  get 'game/add_game/:id' => 'games#add_game' , as: 'add_game'

  root to: "welcome#index"

end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :authenticate_user!

  def index
    @friends = current_user.friends
  end

  def destroy
    @friend = User.find(params[:id])
    current_user.friends.delete @friend
    @friend.friends.delete current_user if @friend.friends.include? current_user
    redirect_to friends_path
  end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/index.html.erb
<h1>Listing friends</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friends.each do |friend| %>
      <% if friend.friends.include? current_user %>
        <tr>
          <td>
            <%= link_to friend.name, profile_path(friend.id) %>
          </td>
          <td>
            <%#= link_to 'Edit', edit_friend_path(friend) %>
          </td>
          <td>
            <%= link_to 'Destroy', friend_path(friend), method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>