config/routes.rb
Rails.application.routes.draw do

  post '/games' => 'game_users#delete', as: 'delete_game_from_user'

  get 'game_user/search' => 'game_users#search', as: 'search'

  post 'game_user/search_result' => 'game_users#search_result', as: 'result'

  resources :user_comments

  get '/comments/:id, :user', to: 'comments#view', as: 'usercomments'

  resources :comments

  resources :friends, only: [:index, :destroy]

  get 'welcome/index'

  resources :home

  resources :game_users

  resources :ratings, only: :update

  resources :games

  resources :profiles

  devise_for :users

  get 'game_user/add_user/:id' => 'game_users#add_user' , as: 'add_user'

  get 'game/add_game/:id' => 'games#add_game' , as: 'add_game'

  root to: "welcome#index"

end

app/models/game_user.rb
class GameUser < ActiveRecord::Base

	belongs_to :game
	belongs_to :user
	has_many :comments
	has_many :users, through: :comments
	has_many  :ratings

	# raty source: http://paweljaniak.co.za/2013/07/25/5-star-ratings-with-rails/
	def average_rating
		ratings.sum(:score) / ratings.size
	end

end

app/controllers/game_users_controller.rb
class GameUsersController < ApplicationController
  before_action :set_game_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /game_users
  # GET /game_users.json
  def index
    @users = User.all
    @game_users = GameUser.all
    @ratings = Rating.all
    @current_user = current_user
    @friends = current_user.friends
    @friendships = Friendship.all
  end

  def add_user

    @friend = Friendship.new
    @friend.user_id = current_user.id
    @friend.friend_id = params[:id]
    #respond_to do |format|
    if @friend.save
        #format.html { redirect_to game_users_path, notice: 'Game user was successfully created.' }
        #format.json { render :show, status: :created, location: game_users_path }
        redirect_to friends_path
      else
        #format.html { render :new }
        #format.json { render json: game_users_path.errors, status: :unprocessable_entity }
      end
    #end 

  end

  def delete
   @game_users = GameUser.where("user_id = ? AND game_id = ?", current_user.id, params[:format]).first
   @game_users.update_column :deleted, true
   redirect_to games_path
  end

  #einagbe seite
  def search
    @games = Game.all
    @search = GameUser.all
  end

  def search_result
    #http://railscasts.com/episodes/37-simple-search-form
    @games = Game.search(params[:search]).first
    @search_input = params[:search]
    if @games.nil?
    else
      @results = GameUser.where("game_id = ?", @games.id)
    end
  end

  # GET /game_users/1
  # GET /game_users/1.json
  def show
  end

  # GET /game_users/new
  def new
    @game_user = GameUser.new
  end

  # GET /game_users/1/edit
  def edit
  end

  # POST /game_users
  # POST /game_users.json
  def create
    @game_user = GameUser.new(game_user_params)

    respond_to do |format|
      if @game_user.save
        format.html { redirect_to @game_user, notice: 'Game user was successfully created.' }
        format.json { render :show, status: :created, location: @game_user }
      else
        format.html { render :new }
        format.json { render json: @game_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /game_users/1
  # PATCH/PUT /game_users/1.json
  def update
    respond_to do |format|
      if @game_user.update(game_user_params)
        format.html { redirect_to @game_user, notice: 'Game user was successfully updated.' }
        format.json { render :show, status: :ok, location: @game_user }
      else
        format.html { render :edit }
        format.json { render json: @game_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /game_users/1
  # DELETE /game_users/1.json
  def destroy
    @game_user.destroy
    respond_to do |format|
      format.html { redirect_to game_users_url, notice: 'Game user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game_user
      @game_user = GameUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_user_params
      params[:game_user]
    end

    #def friendship_user_params
    #  params.require(:friendship).permit(:friend_id, :user_id)
    #end

  end

app/helpers/game_users_helper.rb
module GameUsersHelper
end

app/views/game_users/_form.html.erb
<%= form_for(@game_user) do |f| %>
  <% if @game_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game_user.errors.count, "error") %> prohibited this game_user from being saved:</h2>

      <ul>
      <% @game_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/game_users/edit.html.erb
<h1>Editing game_user</h1>

<%= render 'form' %>

<%= link_to 'Show', @game_user %> |
<%= link_to 'Back', game_users_path %>

app/views/game_users/index.html.erb
<h1>Spielerliste</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>


  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name , profile_path(user.id) %>: </td>
        <% x = user.id %>
        <% @game_users.each do |y| %>
          <%if x == y.user_id && GameUser.all.where("user_id = ? AND game_id= ?", y.user_id, y.game_id).first.deleted == false %>
            <td>
              <!-- Spiele die neu erstellt werden müssen ein rating haben -->
              <%# if y.rating_id == nil %>
                <!-- ] -->
                <%# else %>
                <p>[<%= link_to y.game.name, usercomments_path(y.id, current_user.id) %> 
                 -> Rating:
                <% score = y.average %> ]</p>
                <% stars_off = 5 - score %>
                <% score.times do %>
                  <img src="../assets/star-on.png"></img>
                <% end %>
                <% stars_off.times do %>
                  <img src="../assets/star-off.png"></img>
                <% end %><br>
              <%# end %>
            </td>
          <% end %>
        <% end %>
        <!-- DEBUG AUSGABEN
        <td>
          <%= "current_user.friend? user #{current_user.friend? user}" %>
            <%= "current_user.friend_request_incoming? user #{current_user.friend_request_incoming? user}" %>
            <%= "current_user.friend_request_sent? user #{current_user.friend_request_sent? user}" %>
        </td>
        -->
        <td>
            <% if current_user.friend? user %>
              <%= link_to 'Destroy', friend_path(user), method: :delete, data: { confirm: 'Are you sure?' } %>
            <% elsif current_user.friend_request_incoming? user %>
              <%= link_to "accept friend request", add_user_path(user) %>
            <% elsif current_user.friend_request_sent? user %>
              request sent
            <% elsif user.id == current_user.id %>
              <!-- Nichts bei einem selbst -->
            <% else %>
              <%= link_to "add friend", add_user_path(user) %>
            <% end %>       
        </td>
        <% if current_user.admin? %>
          <td>
              <%= button_to "Cancel account", profile_path(user.id), data: { confirm: "Are you sure?" }, method: :delete %>
          </td>    
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

<% if current_user.admin? %>
  <%= link_to 'New Game user', new_game_user_path %>
<% end %>

app/views/game_users/new.html.erb
<h1>New game_user</h1>

<%= render 'form' %>

<%= link_to 'Back', game_users_path %>

app/views/game_users/search.html.erb
<h1> User search </h1>

<%= @games.last.name %>
<%= @search.last.id %>

<!-- http://railscasts.com/episodes/37-simple-search-form -->
<%= form_tag result_path, :method => 'post' do %>
  Insert game name:
  <p>
     <div class="field">
    	<%= text_field_tag :search, params[:search] %><br>
    	<%= submit_tag "Search", :name => nil %>
  	</div>
  </p>

<% end %>

app/views/game_users/search_result.html.erb
<h1> Results for "<%= @search_input %>"</h1>

<% @ausgabe = false %>

<% if @results.nil? %>
	<% @ausgabe = false %>
<% else %>
	<% @results.each do |result| %>
		<% unless result.deleted? %>
			<% @user = User.where("id = ?", result.user_id).first %>
			<p>
				<%= link_to @user.name , profile_path(@user.id) %>
			</p>
		<% else %>
			<% @ausgabe = true %>
		<% end %>
	<% end %>
<% end %>
<% if @ausgabe == true %>
	No user found
<% end %>
<br><br>
<%= link_to "back", search_path %>

app/views/game_users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_game_user_path(@game_user) %> |
<%= link_to 'Back', game_users_path %>