config/routes.rb
Rails.application.routes.draw do

  post '/games' => 'game_users#delete', as: 'delete_game_from_user'

  get 'game_user/search' => 'game_users#search', as: 'search'

  post 'game_user/search_result' => 'game_users#search_result', as: 'result'

  resources :user_comments

  get '/comments/:id, :user', to: 'comments#view', as: 'usercomments'

  resources :comments

  resources :friends, only: [:index, :destroy]

  get 'welcome/index'

  resources :home

  resources :game_users

  resources :ratings, only: :update

  resources :games

  resources :profiles

  devise_for :users

  get 'game_user/add_user/:id' => 'game_users#add_user' , as: 'add_user'

  get 'game/add_game/:id' => 'games#add_game' , as: 'add_game'

  root to: "welcome#index"

end

app/models/game.rb
class Game < ActiveRecord::Base
	has_many :GameUsers
	has_many :Users, through: :GameUsers

	#http://railscasts.com/episodes/37-simple-search-form
	def self.search(search)
		if search
			where("name LIKE ?", "%#{search}%")
		end
	end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
    @game_users = GameUser.where("user_id = ?", current_user.id)
  end

  def add_game
    @game_users = GameUser.where(user_id: current_user.id, game_id: params[:id]).first
    unless @game_users.nil?
      @game_users.update_column :deleted, false
      redirect_to games_path
    else
      @game = GameUser.new
      @game.user_id = current_user.id
      @game.game_id = params[:id]
      @game.deleted = 'false'
      #respond_to do |format|
        if @game.save
          #format.html { redirect_to game_users_path, notice: 'Game user was successfully created.' }
          #format.json { render :show, status: :created, location: game_users_path }
          redirect_to games_path
        else
          #format.html { render :new }
          #format.json { render json: game_users_path.errors, status: :unprocessable_entity }
        end
      #end 
    end
  end


  # GET /games/1
  # GET /games/1.json
  def show
    @game_users = GameUser.all
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)
    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name, :icon, :description)

    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
   <div class="field">
    <%= f.label :icon %>-url<br>
    <%= f.text_field :icon %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Games</h1>

<table>
  <thead>
    <tr>
      <th>Logo</th>
      <th>Name</th>
      <th>Add/Delete</th>
      <th>Description</th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
      <!-- Link auf game.icon setzen für liste aller Spieler -->
        <td style="background-image: url(<%= game.icon %>); background-size: 100% 100% !important;">
        </td>        
        <td><%= link_to game.name, game %></td>  
        <% unless @game_users.where(user_id: current_user.id, game_id: game.id).first.nil? %>
            <% unless @game_users.where(user_id: current_user.id, game_id: game.id).first.deleted? %>
              <td>
                <%= button_to "delete", delete_game_from_user_path(game.id) %>
              </td>
          <% else %>
            <td>
              <%= link_to "add game", add_game_path(game.id) %>
            </td>
          <% end %>
        <% else %>
          <td>
            <%= link_to "add game", add_game_path(game.id) %>
          </td>
        <% end %>
          <td><%= game.description %></td>
        <% if current_user.admin? %>
          <td><%= link_to 'Edit', edit_game_path(game) %></td>
          <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user.admin? %>
  <%= link_to 'New Game', new_game_path %>
<% end %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<strong>Name:</strong>
	<%= @game.name %>
	<% if @game_users.where("user_id = ? AND game_id = ?", current_user.id, params[:id]).exists? %>
		<td>
			You play the game
		</td>
	<% else %>
		<td>
			You dont play the game
		</td>
	<% end %>
	<br><br>
	<strong>Description:</strong>
	<%= @game.description %>

</p>

<% if current_user.admin? %>
	<%= link_to 'Edit', edit_game_path(@game) %> |
<% end %>
<%= link_to 'Back', games_path %>